name: CI

on:
  # Trigger the workflow on push or pull request events on the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual execution via the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use both the generic "self-hosted" label and your runner-specific label.
    # Since your runner shows as "arc-custom-runners-type2", we include it here.
    runs-on: [self-hosted, arc-custom-runners-type2]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
